import { MESSAGE_SUCCESS_GETALL_ROLE } from './role.messageResponse.js';
import { MESSAGE_SUCCESS_GETALL_ORDER_STATUS } from './orderStatus.messageResponse.js';

const ROLE_RESPONSE_MESSAGE = {
  MESSAGE_SUCCESS_GETALL_ROLE,
};

const ORDER_STATUS_RESPONSE_MESSAGE = {
  MESSAGE_SUCCESS_GETALL_ORDER_STATUS,
};

export { ROLE_RESPONSE_MESSAGE, ORDER_STATUS_RESPONSE_MESSAGE };
