import { MESSAGE_SUCCESS_GETALL_ROLE } from './role.messageResponse.js';
import { MESSAGE_SUCCESS_GETALL_ORDER_STATUS } from './orderStatus.messageResponse.js';
import { MESSAGE_SUCCESS_GETALL_ESTATE_STATUS } from './estateStatus.messageResponse.js';

const ROLE_RESPONSE_MESSAGE = {
  MESSAGE_SUCCESS_GETALL_ROLE,
};

const ORDER_STATUS_RESPONSE_MESSAGE = {
  MESSAGE_SUCCESS_GETALL_ORDER_STATUS,
};
const ESTATE_STATUS_RESPONSE_MESSAGE = {
  MESSAGE_SUCCESS_GETALL_ESTATE_STATUS,
};

export {
  ROLE_RESPONSE_MESSAGE,
  ORDER_STATUS_RESPONSE_MESSAGE,
  ESTATE_STATUS_RESPONSE_MESSAGE,
};
